test: &default
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  app_id: APP-80W284485P519543T
  http_timeout: 30
  mode: sandbox

development:
  <<: *default

with_certificate:
  <<: *default
  username: platfo_1255170694_biz_api1.gmail.com
  password: 2DPPKUPKB7DQLXNR
  signature:
  cert_path: "spec/config/cert_key.pem"
  app_id: APP-80W284485P519543T

with_oauth_token:
  <<: *default
  token: H2kLxjm9lCxQdnOYxkH29I53TpZyIXez4GtHhAVGpiU3DiVTz5eNPQ
  token_secret: MnZ-iPdDqGLEfQIuTIfUN4uK9lU
